"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { ExternalLink, Pencil, Trash2, MessageSquare } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Spinner } from "@/components/ui/Spinner";
import { NotesSection } from "@/components/project/NotesSection";
import { InterviewSummaryPanel } from "@/components/project/InterviewSummaryPanel";
import { TranscriptViewer } from "@/components/project/TranscriptViewer";
import { InterviewModal } from "@/components/interview/InterviewModal";
import { formatRelativeDate } from "@/lib/utils";
import { Project } from "@/lib/types";

export default function ProjectDetailPage() {
  const params = useParams<{ id: string }>();
  const router = useRouter();
  const [project, setProject] = useState<Project | null>(null);
  const [loading, setLoading] = useState(true);
  const [interviewOpen, setInterviewOpen] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [deleteError, setDeleteError] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  // Track whether the summary existed on the initial load so we don't fire
  // summary_viewed immediately after the user just finished creating it.
  const summaryExistedOnMount = useRef<boolean | null>(null);

  const load = useCallback(async () => {
    const res = await fetch(`/api/projects/${params.id}`);
    if (!res.ok) { router.push("/"); return; }
    const data: Project = await res.json();
    setProject(data);
    setLoading(false);

    const hasSummary = Boolean(data.latest_session?.summary);

    // Record whether the summary was present on the very first load.
    if (summaryExistedOnMount.current === null) {
      summaryExistedOnMount.current = hasSummary;
    }

    // Only fire summary_viewed if the summary existed before this session
    // (i.e. was not just generated by the interview we just completed).
    if (hasSummary && summaryExistedOnMount.current) {
      void fetch("/api/analytics", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          event: "summary_viewed",
          properties: { project_id: data.id, session_id: data.latest_session!.id },
        }),
      });
    }

    // Update browser tab title to reflect the project name.
    document.title = `${data.title} — Idea Planner`;
  }, [params.id, router]);

  useEffect(() => {
    load();
    return () => {
      // Reset title when leaving the page.
      document.title = "Idea Planner";
    };
  }, [load]);

  async function deleteProject() {
    setDeleting(true);
    setDeleteError(false);
    const res = await fetch(`/api/projects/${params.id}`, { method: "DELETE" });
    if (!res.ok) {
      setDeleting(false);
      setDeleteError(true);
      setConfirmDelete(false);
      return;
    }
    router.refresh();
    router.push("/");
  }

  if (loading) {
    return (
      <div className="flex justify-center py-24">
        <Spinner className="h-8 w-8" />
      </div>
    );
  }

  if (!project) return null;

  const session = project.latest_session;

  return (
    <div className="mx-auto max-w-2xl space-y-8">
      {/* Header */}
      <div>
        <div className="mb-1 flex items-start justify-between gap-4">
          <h1 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100 leading-tight">
            {project.title}
          </h1>
          <div className="flex shrink-0 items-center gap-2">
            <Link href={`/projects/${project.id}/edit`}>
              <Button variant="ghost" size="sm">
                <Pencil className="h-3.5 w-3.5" />
                Edit
              </Button>
            </Link>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => { setConfirmDelete(true); setDeleteError(false); }}
              disabled={deleting}
              aria-label="Delete project"
            >
              <Trash2 className="h-3.5 w-3.5" />
            </Button>
          </div>
        </div>

        {/* Inline delete confirmation — replaces window.confirm */}
        {confirmDelete && (
          <div className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 dark:border-red-800 dark:bg-red-950/30">
            <p className="mb-3 text-sm text-red-800 dark:text-red-200">
              Delete this project? This cannot be undone.
            </p>
            <div className="flex gap-2">
              <Button size="sm" variant="danger" onClick={deleteProject} disabled={deleting}>
                {deleting ? "Deleting…" : "Yes, delete"}
              </Button>
              <Button size="sm" variant="ghost" onClick={() => setConfirmDelete(false)} disabled={deleting}>
                Cancel
              </Button>
            </div>
          </div>
        )}

        {deleteError && (
          <p className="mt-2 text-sm text-red-500">
            Failed to delete project. Please try again.
          </p>
        )}

        {project.description && (
          <p className="mt-2 text-zinc-600 dark:text-zinc-400">{project.description}</p>
        )}

        <div className="mt-3 flex flex-wrap items-center gap-2">
          {project.tags.map((tag) => (
            <Badge key={tag.id} label={tag.name} />
          ))}
          {project.github_url && (
            <a
              href={project.github_url}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 rounded-full border border-zinc-200 px-2.5 py-0.5 text-xs text-zinc-600 hover:border-zinc-400 hover:text-zinc-900 dark:border-zinc-700 dark:text-zinc-400 dark:hover:text-zinc-100 transition-colors"
            >
              <ExternalLink className="h-3.5 w-3.5" />
              GitHub
            </a>
          )}
        </div>

        <p className="mt-2 text-xs text-zinc-400 dark:text-zinc-500">
          Updated {formatRelativeDate(project.updated_at)}
        </p>
      </div>

      {/* AI Interview card */}
      <div className="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-800">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="font-semibold text-zinc-900 dark:text-zinc-100">AI Interview</h2>
            <p className="text-sm text-zinc-500 dark:text-zinc-400">
              {session?.status === "completed"
                ? "Interview complete — summary saved below"
                : "Chat with AI to develop this idea"}
            </p>
          </div>
          <Button onClick={() => setInterviewOpen(true)}>
            <MessageSquare className="h-4 w-4" />
            {session ? "New interview" : "Start interview"}
          </Button>
        </div>
      </div>

      {/* AI Summary */}
      {session?.summary && <InterviewSummaryPanel summary={session.summary} />}

      {/* Transcript */}
      {session?.messages && session.messages.length > 0 && (
        <TranscriptViewer messages={session.messages} />
      )}

      {/* Notes */}
      <NotesSection projectId={project.id} initialNotes={project.notes} />

      <InterviewModal
        projectId={project.id}
        open={interviewOpen}
        onClose={() => {
          setInterviewOpen(false);
          // After closing the modal, mark that any newly-present summary was
          // just created in this session, so summary_viewed fires correctly
          // on the next independent page load rather than right now.
          summaryExistedOnMount.current = null;
          load();
        }}
      />
    </div>
  );
}
